In [1]:
import sys
print(sys.version)

3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)]

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

#import seaborn as sns

import numpy as np
from scipy.stats import norm
#from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [4]:
cuip_sample_data = pd.read_csv("./CSCDC+Dataset+Preview/video_event_csv/all.csv", header=0, sep=",")
cuip_sample_data.tail()

,Unnamed: 0,camera_id,hit_counts,id,intersection,label,locations,pole_id,timestamp,timestamp-iso
8768,8768,mlk-douglas-cam-1,5,c7c02447-98c9-4f58-8ca9-07c3f193e572,True,car,"[{'coords': [980.7373979562243, 283.8338305011...",mlk-douglas-1,1559407602464,2019-06-01 16:46:42.464
8769,8769,mlk-douglas-cam-1,6,93e57c00-3e0f-44ed-9ea6-2dfc1a4fbfaa,True,car,"[{'coords': [235.762401627538, 392.14333282187...",mlk-douglas-1,1559407602464,2019-06-01 16:46:42.464
8770,8770,mlk-douglas-cam-1,2,d0554f0e-b0b5-4096-9546-3a7e5dae705d,True,car,"[{'coords': [1423.9130351823123, 290.657910023...",mlk-douglas-1,1559407602005,2019-06-01 16:46:42.005
8771,8771,mlk-douglas-cam-1,2,07263aa9-518e-4431-82d1-2aa0ba96a9d3,True,car,"[{'coords': [1599.856265115459, 290.9150280946...",mlk-douglas-1,1559407607749,2019-06-01 16:46:47.749
8772,8772,mlk-douglas-cam-1,10,b5a29a19-3cc8-4cc9-855b-8f6747fb8792,True,car,"[{'coords': [330.7116451578009, 316.6969818675...",mlk-douglas-1,1559407607749,2019-06-01 16:46:47.749

In [5]:
cuip_sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8773 entries, 0 to 8772
Data columns (total 10 columns):
Unnamed: 0       8773 non-null int64
camera_id        8773 non-null object
hit_counts       8773 non-null int64
id               8773 non-null object
intersection     8773 non-null bool
label            8773 non-null object
locations        8773 non-null object
pole_id          8773 non-null object
timestamp        8773 non-null int64
timestamp-iso    8773 non-null object
dtypes: bool(1), int64(3), object(6)
memory usage: 625.5+ KB

In [6]:
cuip_sample_data['datetime'] = pd.to_datetime(cuip_sample_data['timestamp-iso'])
# Set the datetime column as the index
cuip_sample_data.index = cuip_sample_data['datetime'] 
cuip_sample_data.head()

,Unnamed: 0,camera_id,hit_counts,id,intersection,label,locations,pole_id,timestamp,timestamp-iso,datetime
datetime,,,,,,,,,,,
2019-06-01 16:56:45.612,0,mlk-central-cam-2,7,f033bc3e-23af-40ed-96f5-42ab65438365,True,car,"[{'coords': [492.9353299755912, 429.0977290358...",mlk-central-2,1559408205612,2019-06-01 16:56:45.612,2019-06-01 16:56:45.612
2019-06-01 16:57:19.356,1,mlk-central-cam-2,3,63087161-a9b2-4ce3-8855-f6b2d9e522b7,True,car,"[{'coords': [804.2193175325589, 541.1222384279...",mlk-central-2,1559408239356,2019-06-01 16:57:19.356,2019-06-01 16:57:19.356
2019-06-01 16:57:08.087,2,mlk-central-cam-2,9,747c54e5-8b74-43d7-864c-fd0b20d6719d,True,car,"[{'coords': [342.9593716503662, 393.3884433472...",mlk-central-2,1559408228087,2019-06-01 16:57:08.087,2019-06-01 16:57:08.087
2019-06-01 16:57:46.286,3,mlk-central-cam-2,4,5d292293-fa4a-431a-bdbd-d0d99d138ad8,True,car,"[{'coords': [1348.9825900032183, 413.021423951...",mlk-central-2,1559408266286,2019-06-01 16:57:46.286,2019-06-01 16:57:46.286
2019-06-01 16:56:02.471,4,mlk-central-cam-2,4,f228b14f-b940-4ca9-a88f-8634fa6a10c6,True,car,"[{'coords': [339.72799855062664, 365.740940441...",mlk-central-2,1559408162471,2019-06-01 16:56:02.471,2019-06-01 16:56:02.471

In [7]:
cuip_sample_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8773 entries, 2019-06-01 16:56:45.612000 to 2019-06-01 16:46:47.749000
Data columns (total 11 columns):
Unnamed: 0       8773 non-null int64
camera_id        8773 non-null object
hit_counts       8773 non-null int64
id               8773 non-null object
intersection     8773 non-null bool
label            8773 non-null object
locations        8773 non-null object
pole_id          8773 non-null object
timestamp        8773 non-null int64
timestamp-iso    8773 non-null object
datetime         8773 non-null datetime64[ns]
dtypes: bool(1), datetime64[ns](1), int64(3), object(6)
memory usage: 762.5+ KB

In [8]:
colsPlot = cuip_sample_data.resample('H').sum()
colsPlot.tail()

                     Unnamed: 0  hit_counts  intersection          timestamp
datetime
2019-06-01 16:00:00    38478378       39031        6622.0  13680673731038580

In [9]:
cuip_sample_data_cars = cuip_sample_data[ cuip_sample_data['label'] == 'bus' ]
cuip_sample_data_cars.head()

,Unnamed: 0,camera_id,hit_counts,id,intersection,label,locations,pole_id,timestamp,timestamp-iso,datetime
datetime,,,,,,,,,,,
2019-06-01 16:17:41.786,235,mlk-central-cam-2,15,7b7ecf97-24df-4a86-a224-5120b71dec17,True,bus,"[{'coords': [1322.2695768368044, 358.430221071...",mlk-central-2,1559405861786,2019-06-01 16:17:41.786,2019-06-01 16:17:41.786
2019-06-01 16:22:09.754,397,mlk-lindsay-cam-2,2,75dbfe94-934d-46e5-a14e-373a2d517648,True,bus,"[{'coords': [413.6200735047607, 272.1207930655...",mlk-lindsay-2,1559406129754,2019-06-01 16:22:09.754,2019-06-01 16:22:09.754
2019-06-01 16:54:27.800,511,mlk-georgia-cam-1,7,d66ff351-4a0c-46b6-8e14-df4ade0519dc,False,bus,"[{'coords': [64.01453910776297, 219.1430668898...",mlk-georgia-1,1559408067800,2019-06-01 16:54:27.800,2019-06-01 16:54:27.800
2019-06-01 16:39:37.310,1598,mlk-peeples-cam-1,27,fd9e77b2-e96c-4b90-b15a-ab62aa61071d,True,bus,"[{'coords': [1649.6463260439482, 353.821053196...",mlk-peeples-1,1559407177310,2019-06-01 16:39:37.310,2019-06-01 16:39:37.310
2019-06-01 16:55:33.328,1663,mlk-houston-cam-1,4,a0552d3e-ea42-4ea1-95c9-7ca3bb6bdc6b,True,bus,"[{'coords': [610.2196179749221, 325.8935772595...",mlk-houston-1,1559408133328,2019-06-01 16:55:33.328,2019-06-01 16:55:33.328